### GET Request
GET http://localhost:3001/api/v1/blogs/63729da1fad1f2c6669255c6 HTTP/1.1

### POST Request
POST http://localhost:3001/api/v1/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer 

{
    "title": "Created by Hellas: 3",
    "author": "Arto Hellas",
    "url": "https://www.google.com",
    "likes": 20
}

### PUT Request
PUT http://localhost:3001/api/v1/blogs/63728fe5d1fc749d89b95d10 HTTP/1.1
Content-Type: application/json
Authorization: bearer 

{
    "title": "This has been updated by Hellas",
    "author": "Marc",
    "url": "https://www.google.com",
    "likes": 35
}

### DELETE Request
DELETE http://localhost:3001/api/v1/blogs/63728fe5d1fc989b95d10 HTTP/1.1
Authorization: bearer 